//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "courses")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_courses_mentor_name_unique")]
    pub mentor_id: i32,
    #[sea_orm(unique_key = "idx_courses_mentor_name_unique")]
    pub name: String,
    pub duration: String,
    pub description: String,
    pub status: String,
    pub enrolled_mentees_count: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::announcements::Entity")]
    Announcements,
    #[sea_orm(has_many = "super::course_enrollments::Entity")]
    CourseEnrollments,
    #[sea_orm(has_many = "super::lessons::Entity")]
    Lessons,
    #[sea_orm(has_many = "super::tasks::Entity")]
    Tasks,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::MentorId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::announcements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Announcements.def()
    }
}

impl Related<super::course_enrollments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseEnrollments.def()
    }
}

impl Related<super::lessons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Lessons.def()
    }
}

impl Related<super::tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tasks.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
