//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "email_queue")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub recipient: String,
    pub recipient_name: Option<String>,
    pub email_type: String,
    pub subject: String,
    #[sea_orm(column_type = "Text")]
    pub html_content: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub text_content: Option<String>,
    pub metadata: Option<Json>,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub retry_count: Option<i32>,
    pub max_retries: Option<i32>,
    pub next_retry_at: Option<DateTimeWithTimeZone>,
    pub sent_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
