//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::announcements::Entity as Announcements;
pub use super::contract_files::Entity as ContractFiles;
pub use super::course_enrollments::Entity as CourseEnrollments;
pub use super::courses::Entity as Courses;
pub use super::email_queue::Entity as EmailQueue;
pub use super::lesson_progress::Entity as LessonProgress;
pub use super::lessons::Entity as Lessons;
pub use super::mentor_mentee_relationships::Entity as MentorMenteeRelationships;
pub use super::messages::Entity as Messages;
pub use super::task_submissions::Entity as TaskSubmissions;
pub use super::tasks::Entity as Tasks;
pub use super::users::Entity as Users;
