//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pid: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    #[sea_orm(unique)]
    pub api_key: String,
    pub name: String,
    pub reset_token: Option<String>,
    pub reset_sent_at: Option<DateTimeWithTimeZone>,
    pub email_verification_token: Option<String>,
    pub email_verification_sent_at: Option<DateTimeWithTimeZone>,
    pub email_verified_at: Option<DateTimeWithTimeZone>,
    pub magic_link_token: Option<String>,
    pub magic_link_expiration: Option<DateTimeWithTimeZone>,
    pub role: String,
    pub membership_category: String,
    pub career_path: Option<String>,
    pub specialization: Option<String>,
    pub status: String,
    pub membership_enabled: bool,
    pub membership_amount: Option<Decimal>,
    pub membership_paid: bool,
    pub payment_reference: Option<String>,
    pub payment_date: Option<DateTimeWithTimeZone>,
    pub contract_file_url: Option<String>,
    pub community_link: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::announcements::Entity")]
    Announcements,
    #[sea_orm(has_many = "super::contract_files::Entity")]
    ContractFiles,
    #[sea_orm(has_many = "super::course_enrollments::Entity")]
    CourseEnrollments,
    #[sea_orm(has_many = "super::courses::Entity")]
    Courses,
    #[sea_orm(has_many = "super::lesson_progress::Entity")]
    LessonProgress,
    #[sea_orm(has_many = "super::lessons::Entity")]
    Lessons,
    #[sea_orm(has_many = "super::task_submissions::Entity")]
    TaskSubmissions,
    #[sea_orm(has_many = "super::tasks::Entity")]
    Tasks,
}

impl Related<super::announcements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Announcements.def()
    }
}

impl Related<super::contract_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContractFiles.def()
    }
}

impl Related<super::course_enrollments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseEnrollments.def()
    }
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl Related<super::lesson_progress::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LessonProgress.def()
    }
}

impl Related<super::lessons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Lessons.def()
    }
}

impl Related<super::task_submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaskSubmissions.def()
    }
}

impl Related<super::tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tasks.def()
    }
}
